#!/usr/bin/env node
/**
 * AWSops v2 — `make configure`
 *
 * Interactive configurator that asks the operator which VPC to deploy into
 * (new or existing) and writes Terraform inputs for the v2 `foundation` module:
 *   - terraform/v2/foundation/terraform.tfvars
 *   - terraform/v2/foundation/backend.hcl
 *
 * Mirrors the VPC-selection UX of the v1 script scripts/00-deploy-infra.sh.
 *
 * AWS access is done by shelling out to the `aws` CLI (already installed) — no
 * AWS SDK dependency. The TUI uses @inquirer/prompts.
 *
 * Run:  node scripts/v2/configure.mjs   (or: make configure)
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { input, select, checkbox, confirm } from '@inquirer/prompts';

const REGION = process.env.AWS_REGION || 'ap-northeast-2';

// Repo-root-relative output paths. This file lives at scripts/v2/configure.mjs,
// so the repo root is two directories up.
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');
const FOUNDATION_DIR = join(REPO_ROOT, 'terraform', 'v2', 'foundation');
const TFVARS_PATH = join(FOUNDATION_DIR, 'terraform.tfvars');
const BACKEND_PATH = join(FOUNDATION_DIR, 'backend.hcl');

const CIDR_RE = /^\d+\.\d+\.\d+\.\d+\/\d+$/;

// ---------------------------------------------------------------------------
// AWS helpers — shell out to the aws CLI and JSON.parse the output.
// ---------------------------------------------------------------------------

/** Run `aws <args...>` and return stdout as a string. Throws on non-zero exit. */
function aws(args) {
  return execFileSync('aws', args, {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  });
}

/** Run `aws <args...> --output json` and return the parsed JSON object. */
function awsJson(args) {
  return JSON.parse(aws([...args, '--output', 'json']));
}

/** Name tag value for an object with a Tags array, or a fallback string. */
function nameTag(obj, fallback) {
  const tags = obj.Tags || [];
  const t = tags.find((x) => x.Key === 'Name');
  return t && t.Value ? t.Value : fallback;
}

function describeVpcs() {
  const data = awsJson(['ec2', 'describe-vpcs', '--region', REGION]);
  return data.Vpcs || [];
}

function describeSubnets(vpcId) {
  const data = awsJson([
    'ec2',
    'describe-subnets',
    '--filters',
    `Name=vpc-id,Values=${vpcId}`,
    '--region',
    REGION,
  ]);
  return data.Subnets || [];
}

/** Returns the list of available NAT Gateway IDs in the given VPC. */
function describeNatGatewayIds(vpcId) {
  const out = aws([
    'ec2',
    'describe-nat-gateways',
    '--filter',
    `Name=vpc-id,Values=${vpcId}`,
    'Name=state,Values=available',
    '--query',
    'NatGateways[*].NatGatewayId',
    '--output',
    'text',
    '--region',
    REGION,
  ]);
  // --output text gives whitespace-separated ids (empty string when none).
  return out.split(/\s+/).filter(Boolean);
}

/** List EKS cluster names in REGION. */
function listEksClusters() {
  const data = awsJson(['eks', 'list-clusters', '--region', REGION]);
  return data.clusters || [];
}

/** Cluster authentication mode (API / API_AND_CONFIG_MAP / CONFIG_MAP). */
function eksAuthMode(name) {
  try {
    const d = awsJson(['eks', 'describe-cluster', '--name', name, '--region', REGION]);
    return (d.cluster && d.cluster.accessConfig && d.cluster.accessConfig.authenticationMode) || 'CONFIG_MAP';
  } catch {
    return 'UNKNOWN';
  }
}

// ---------------------------------------------------------------------------
// HCL writers
// ---------------------------------------------------------------------------

function hclString(v) {
  return `"${String(v).replace(/"/g, '\\"')}"`;
}

function hclStringList(arr) {
  return `[${arr.map(hclString).join(', ')}]`;
}

/**
 * Build terraform.tfvars content.
 * For an existing VPC, vpc_cidr is intentionally omitted — the foundation
 * module derives it via data.aws_vpc.existing when create_network = false.
 */
function buildTfvars(cfg) {
  const lines = [
    '# Generated by `make configure` (scripts/v2/configure.mjs). Do not commit.',
  ];
  if (cfg.createNetwork) {
    lines.push(`domain_name      = ${hclString(cfg.domainName)}`);
    lines.push(`hosted_zone_name = ${hclString(cfg.hostedZoneName)}`);
    lines.push(`create_network   = true`);
    lines.push(`vpc_cidr         = ${hclString(cfg.vpcCidr)}`);
  } else {
    lines.push(`domain_name                 = ${hclString(cfg.domainName)}`);
    lines.push(`hosted_zone_name            = ${hclString(cfg.hostedZoneName)}`);
    lines.push(`create_network              = false`);
    lines.push(`existing_vpc_id             = ${hclString(cfg.existingVpcId)}`);
    lines.push(
      `existing_private_subnet_ids = ${hclStringList(cfg.existingPrivateSubnetIds)}`,
    );
  }
  if (cfg.onboardEksClusters && cfg.onboardEksClusters.length > 0) {
    lines.push(`onboard_eks_clusters = ${hclStringList(cfg.onboardEksClusters)}`);
  }
  // Feature-flag gates. All default false in TF (absent ⇒ 0 resources/$0), so emit ONLY when enabled.
  // These were previously hand-added to terraform.tfvars and silently lost on a `make configure`
  // regenerate (→ a follow-up apply would destroy the gated infra); they are now first-class here.
  if (cfg.agentcoreEnabled) lines.push('agentcore_enabled         = true');
  if (cfg.integrationsEnabled) lines.push('integrations_enabled      = true'); // ADR-039 P2-infra inc2 (needs agentcore)
  if (cfg.workersEnabled) lines.push('workers_enabled           = true');
  if (cfg.steampipeEnabled) lines.push('steampipe_enabled         = true');
  if (cfg.hybridRoutingEnabled) lines.push('hybrid_routing_enabled    = true');
  if (cfg.eksAutoRegisterEnabled) lines.push('eks_auto_register_enabled = true'); // needs workers
  return lines.join('\n') + '\n';
}

/**
 * Read a boolean flag from an EXISTING terraform.tfvars (true iff `<name> = true`). Used to pre-select
 * the current live value when re-running `make configure`, so an already-enabled flag is never silently
 * dropped (the footgun). A missing file (fresh / OSS install) ⇒ false (the OSS-safe default).
 */
function readExistingFlag(name) {
  try {
    const txt = readFileSync(TFVARS_PATH, 'utf8');
    return new RegExp(`^\\s*${name}\\s*=\\s*true\\b`, 'm').test(txt);
  } catch {
    return false;
  }
}

function buildBackendHcl(cfg) {
  return [
    `bucket       = ${hclString(cfg.stateBucket)}`,
    `key          = "foundation/terraform.tfstate"`,
    `region       = ${hclString(REGION)}`,
    `encrypt      = true`,
    `use_lockfile = true`,
  ].join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Main flow
// ---------------------------------------------------------------------------

async function main() {
  console.log('');
  console.log('AWSops v2 — configure (foundation)');
  console.log(`Region: ${REGION}  (override with AWS_REGION)`);
  console.log('');

  const domainName = await input({
    message: 'Public domain name (CloudFront FQDN):',
    default: 'v2.example.com',
  });

  const hostedZoneName = await input({
    message: 'Route53 hosted zone name:',
    default: 'example.com',
  });

  const stateBucket = await input({
    message: 'Terraform state S3 bucket:',
    default: 'awsops-v2-tfstate',
  });

  let vpcMode = await select({
    message: 'VPC option:',
    choices: [
      { name: 'Create new VPC', value: 'new' },
      { name: 'Use existing VPC', value: 'existing' },
    ],
    default: 'new',
  });

  let createNetwork = true;
  let vpcCidr = '';
  let existingVpcId = '';
  let existingPrivateSubnetIds = [];

  if (vpcMode === 'existing') {
    console.log('');
    console.log(`Listing VPCs in ${REGION}...`);
    const vpcs = describeVpcs();

    if (vpcs.length === 0) {
      console.log(
        '  No VPCs found in this region. Falling back to creating a new VPC.',
      );
      vpcMode = 'new';
    } else {
      existingVpcId = await select({
        message: 'Select VPC:',
        choices: vpcs.map((v) => {
          const name = nameTag(v, '(no name)');
          const dflt = v.IsDefault ? ' [default]' : '';
          return {
            name: `${v.VpcId}  ${v.CidrBlock || '?'}  ${name}${dflt}`,
            value: v.VpcId,
          };
        }),
      });
      createNetwork = false;

      // Private subnets = MapPublicIpOnLaunch === false.
      console.log('');
      console.log(`Listing subnets for ${existingVpcId}...`);
      const subnets = describeSubnets(existingVpcId);
      const privateSubnets = subnets.filter(
        (s) => s.MapPublicIpOnLaunch === false,
      );

      if (privateSubnets.length < 2) {
        throw new Error(
          `VPC ${existingVpcId} has ${privateSubnets.length} private subnet(s) ` +
            `(MapPublicIpOnLaunch=false). At least 2 across >=2 AZs are required ` +
            `for the foundation module. Pick a different VPC or create a new one.`,
        );
      }

      // Re-prompt until the operator picks >=2 subnets spanning >=2 AZs.
      for (;;) {
        existingPrivateSubnetIds = await checkbox({
          message:
            'Select private subnets (>=2 across >=2 AZs) for ALB/Fargate:',
          choices: privateSubnets.map((s) => {
            const name = nameTag(s, '(no name)');
            return {
              name: `${s.SubnetId}  ${s.AvailabilityZone}  ${name}`,
              value: s.SubnetId,
            };
          }),
        });

        if (existingPrivateSubnetIds.length < 2) {
          console.log(
            '  Need at least 2 private subnets selected. Please try again.',
          );
          continue;
        }
        const selectedAzs = new Set(
          privateSubnets
            .filter((s) => existingPrivateSubnetIds.includes(s.SubnetId))
            .map((s) => s.AvailabilityZone),
        );
        if (selectedAzs.size < 2) {
          console.log(
            '  Selected subnets must span at least 2 Availability Zones. Please try again.',
          );
          continue;
        }
        break;
      }

      // NAT egress check — private subnets need NAT so Fargate can reach ECR.
      console.log('');
      console.log('Checking NAT Gateways...');
      const natIds = describeNatGatewayIds(existingVpcId);
      if (natIds.length === 0) {
        console.log('');
        console.log(
          '  WARNING: No available NAT Gateway found in this VPC.',
        );
        console.log(
          '  The selected private subnets have no NAT egress, so Fargate tasks',
        );
        console.log(
          '  will NOT be able to pull container images from ECR (and other',
        );
        console.log(
          '  outbound calls will fail) unless interface/gateway VPC endpoints',
        );
        console.log('  are configured.');
        console.log('');
        const proceed = await confirm({
          message: 'Proceed anyway with these subnets?',
          default: false,
        });
        if (!proceed) {
          console.log('Aborted. No files written.');
          process.exit(1);
        }
      } else {
        console.log(`  NAT Gateway(s) available: ${natIds.join(', ')}`);
      }
    }
  }

  if (vpcMode === 'new') {
    createNetwork = true;
    existingVpcId = '';
    existingPrivateSubnetIds = [];
    vpcCidr = await input({
      message: 'New VPC CIDR:',
      default: '10.30.0.0/16',
      validate: (val) =>
        CIDR_RE.test(val.trim()) || 'Invalid CIDR format (expected a.b.c.d/n).',
    });
    vpcCidr = vpcCidr.trim();
  }

  // EKS onboarding (optional). Access Entry requires an API-capable auth mode.
  let onboardEksClusters = [];
  console.log('');
  console.log(`Discovering EKS clusters in ${REGION}...`);
  const eksClusters = listEksClusters();
  if (eksClusters.length === 0) {
    console.log('  No EKS clusters found. Skipping EKS onboarding.');
  } else {
    const usable = [];
    const handoff = [];
    for (const name of eksClusters) {
      const mode = eksAuthMode(name);
      (mode.startsWith('API') ? usable : handoff).push({ name, mode });
    }
    if (handoff.length > 0) {
      console.log('');
      console.log('  These clusters are CONFIG_MAP-only (Access Entry unavailable).');
      console.log('  Switch them to API_AND_CONFIG_MAP, or grant access manually:');
      handoff.forEach((c) => console.log(`    - ${c.name} (${c.mode})`));
    }
    if (usable.length > 0) {
      onboardEksClusters = await checkbox({
        message: 'Select EKS clusters to grant the dashboard read access (Access Entry):',
        choices: usable.map((c) => ({ name: `${c.name}  (${c.mode})`, value: c.name })),
      });
    }
  }

  // Feature-flag gates (all default false in TF). Each prompt PRE-SELECTS the current value from an
  // existing terraform.tfvars, so re-running `make configure` on a live deploy never silently drops an
  // already-enabled flag (which would destroy the gated infra on the next apply). Fresh install ⇒ false.
  console.log('');
  const agentcoreEnabled = await confirm({
    message: 'Provision the AgentCore skeleton (9 gateways + runtime + slice tools)? You run `make agentcore` after apply.',
    default: readExistingFlag('agentcore_enabled'),
  });
  // ADR-039 P2-infra inc2 — egress Integrations (live external-MCP connect; scoped Secrets Manager +
  // dedicated KMS). Only meaningful with AgentCore (the TF local is agentcore_enabled && integrations_enabled).
  const integrationsEnabled = agentcoreEnabled
    ? await confirm({
        message: 'Enable egress Integrations (live external-MCP connect; scoped Secrets Manager + dedicated KMS)?',
        default: readExistingFlag('integrations_enabled'),
      })
    : false;
  const workersEnabled = await confirm({
    message: 'Enable the async worker backbone (SQS + Step Functions + Lambda/Fargate)? (P2)',
    default: readExistingFlag('workers_enabled'),
  });
  const steampipeEnabled = await confirm({
    message: 'Enable the Steampipe inventory data layer (warm Fargate + sync Lambda)?',
    default: readExistingFlag('steampipe_enabled'),
  });
  const hybridRoutingEnabled = await confirm({
    message: 'Enable hybrid chat routing (ADR-038 regex + Haiku classifier)?',
    default: readExistingFlag('hybrid_routing_enabled'),
  });
  // eks_auto_register reuses the workers pg8000 layer → only offered when workers are on.
  const eksAutoRegisterEnabled = workersEnabled
    ? await confirm({
        message: 'Enable EKS CLI auto-register (EventBridge → Lambda → eks_registrations)?',
        default: readExistingFlag('eks_auto_register_enabled'),
      })
    : false;

  const cfg = {
    domainName: domainName.trim(),
    hostedZoneName: hostedZoneName.trim(),
    stateBucket: stateBucket.trim(),
    createNetwork,
    vpcCidr,
    existingVpcId,
    existingPrivateSubnetIds,
    onboardEksClusters,
    agentcoreEnabled,
    integrationsEnabled,
    workersEnabled,
    steampipeEnabled,
    hybridRoutingEnabled,
    eksAutoRegisterEnabled,
  };

  // Summary
  console.log('');
  console.log('Summary');
  console.log('-------');
  console.log(`  domain_name      : ${cfg.domainName}`);
  console.log(`  hosted_zone_name : ${cfg.hostedZoneName}`);
  console.log(`  state_bucket     : ${cfg.stateBucket}`);
  console.log(`  region           : ${REGION}`);
  if (cfg.createNetwork) {
    console.log(`  VPC              : create new`);
    console.log(`  vpc_cidr         : ${cfg.vpcCidr}`);
  } else {
    console.log(`  VPC              : existing (${cfg.existingVpcId})`);
    console.log(
      `  private subnets  : ${cfg.existingPrivateSubnetIds.join(', ')}`,
    );
  }
  console.log(
    `  EKS onboard      : ${cfg.onboardEksClusters.length ? cfg.onboardEksClusters.join(', ') : '(none)'}`,
  );
  console.log(`  AgentCore        : ${cfg.agentcoreEnabled ? 'enabled' : '(disabled)'}`);
  console.log(`  Integrations     : ${cfg.integrationsEnabled ? 'enabled' : '(disabled)'}`);
  console.log(`  Workers          : ${cfg.workersEnabled ? 'enabled' : '(disabled)'}`);
  console.log(`  Steampipe        : ${cfg.steampipeEnabled ? 'enabled' : '(disabled)'}`);
  console.log(`  Hybrid routing   : ${cfg.hybridRoutingEnabled ? 'enabled' : '(disabled)'}`);
  console.log(`  EKS auto-register: ${cfg.eksAutoRegisterEnabled ? 'enabled' : '(disabled)'}`);
  console.log('');
  console.log(`  -> ${TFVARS_PATH}`);
  console.log(`  -> ${BACKEND_PATH}`);
  console.log('');

  const ok = await confirm({
    message: 'Write these files?',
    default: true,
  });
  if (!ok) {
    console.log('Aborted. No files written.');
    process.exit(1);
  }

  mkdirSync(FOUNDATION_DIR, { recursive: true });
  writeFileSync(TFVARS_PATH, buildTfvars(cfg));
  writeFileSync(BACKEND_PATH, buildBackendHcl(cfg));

  console.log('');
  console.log('Wrote:');
  console.log(`  ${TFVARS_PATH}`);
  console.log(`  ${BACKEND_PATH}`);
  console.log('');
  console.log('Next steps:');
  console.log(
    '  cd terraform/v2/foundation && terraform init -backend-config=backend.hcl && terraform plan',
  );
  console.log('');
}

main().catch((err) => {
  // @inquirer/prompts throws ExitPromptError on Ctrl-C — treat as a clean exit.
  if (err && err.name === 'ExitPromptError') {
    console.log('\nCancelled. No files written.');
    process.exit(130);
  }
  console.error(`\nError: ${err && err.message ? err.message : err}`);
  process.exit(1);
});
